### ISSUE TITLE
Pillow fails during docker build

### ISSUE THREAD

**Issue by morriscode** [xme/emlrender#3]
Step 9/18 : RUN pip3 install pillow
 ---> Running in 4490f2c5b3f2
Collecting pillow
  Downloading https://files.pythonhosted.org/packages/2b/06/93bf1626ef36815010e971a5ce90f49919d84ab5d2fa310329f843a74bc1/Pillow-8.0.1.tar.gz (44.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_v_le2ma/pillow/setup.py", line 42
        f"Pillow {PILLOW_VERSION} does not support Python "
                                                          ^
    SyntaxError: invalid syntax

**Comment by morriscode** [comment]
Fixed it by upgrading pip prior to the pillow install
 32 # Install PIL library
 33 #
 34 **RUN pip3 install --upgrade pip**
 35 RUN pip3 install pillow
